Kad_LVS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scores_fixtures.urls')),
    path('auth/', include('lvs_auth.urls')),
   
    path('tournament/', include('tournament.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

lvs_auth/urls.py
from django.urls import path
from . views import (LoginView, DashboardView,TeamsView, 
                     TeamPlayers, DeleteTeam, UpdateMatchScoreV, UpdateTeam, 
                      DeletePlayer, UpdatePlayer, 
                      UpdateMatch)


app_name = 'auth'
urlpatterns = [
    path('login/', LoginView.as_view(), name="login"),
    path('dashboard/', DashboardView.as_view(), name="dashboard"),
    path('teams/', TeamsView.as_view(), name='team'),
    path('teams/<str:pk>/update/', UpdateTeam.as_view(), name='update_team'),
    path('teams/<str:pk>/delete/', DeleteTeam.as_view(), name='delete_team'),
    # path('add-team/', TeamFormView.as_view(), name='team_form'),
    path('<str:pk>/players/', TeamPlayers.as_view(), name='team_players'),
    # path('players/<int:pk>/update/', updatePlayer(), name='update_player'),
    path('players/<int:pk>/update/', UpdatePlayer.as_view(), name='update_player'),
    path('players/<int:pk>/delete/', DeletePlayer.as_view(), name='delete_player'),

    path('match/<int:pk>/update/', UpdateMatch.as_view(), name="update_match"),
    path('score/<int:pk>/update/', UpdateMatchScoreV.as_view(), name="update_match_score")
]

scores_fixtures/urls.py
from django.urls import path
from .views import (HomeViewL, FixturesView, 
                    DeleteFixtureView, UpdateFixtureView,
                    MatchesView, MatchSummary)

app_name = 'scores'
urlpatterns = [
    # path('', HomeView.as_view(), name='index'),
    path('', HomeViewL.as_view(), name='index'),
    path('fixtures/<str:template_name>/', FixturesView.as_view(), name='fixtures'),
    path('fixtures/<str:template_name>/update/<int:pk>/',UpdateFixtureView.as_view(), name='update_fixture'),
    path('fixtures/<str:template_name>/delete/<int:pk>/', DeleteFixtureView.as_view(), name='delete_fixture'),
    path('matches/<str:template_name>/', MatchesView.as_view(), name='matches'),
    path('matches/summary/<int:pk>/', MatchSummary.as_view(), name='match_summary'),
]

lvs_auth/models.py
from django.db import models

# Create your models here.

lvs_auth/views.py
import datetime
from typing import Any, Dict
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.forms.forms import BaseForm
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views.generic import (View, ListView, FormView,
                                  TemplateView, DeleteView, UpdateView)
from django.contrib.messages.views import SuccessMessageMixin

from scores_fixtures.models import Match, MatchStats, Fixture

from .forms import (LoginForm, TeamForm,TeamPlayerForm, TeamUpdateForm,
                    Tournament, UpdateGoalScorerForm, UpdateCardBookingForm,
                    UpdateMatchForm, UpdateMatchStatusForm, UpdateMatchStatForm, AdditionalInfoForm)
from tournament.models import Team, Player


# Create your views here.
class LoginView(View):
    template_name = 'lvs_auth/login.html'

    def get(self, request):
        form = LoginForm()
        return render(request, self.template_name, {'form':form})

    def post(self, request):
        form = LoginForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('scores:index')
            else:
                messages.error(request, "User not found!")

        return render(request, self.template_name, {'form':form})

class DashboardView(TemplateView):
    def get(self, request):
        return render(request, 'lvs_auth/dashboard.html')

class TeamsView(ListView, FormView):
    model = Team
    context_object_name = "teams"
    template_name = 'lvs_auth/teams.html'
    object_list = Team.objects.all()

    form_class = TeamForm
    success_url = '/auth/teams/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tournaments = Tournament.objects.all()
        if tournaments:
            context['tournaments'] = tournaments
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            form.save_m2m()
            messages.success(self.request, "Team Succesfully Added")
            return redirect("auth:team")
        else:
            messages.error(self.request, f"An error occured: {form.errors}")
            return self.form_invalid(form)

class DeleteTeam(SuccessMessageMixin, DeleteView):
    model = Team
    success_message = 'Team Deleted Successfully'

    def get_success_url(self):
        return reverse_lazy('auth:team')

class UpdateTeam(SuccessMessageMixin, UpdateView):
    model = Team
    template_name = "lvs_auth/update_team.html"
    form_class = TeamUpdateForm
    success_message = "Team detail updated"

    def get(self, request, pk, *args, **kwargs):
        team_detail = Team.objects.get(team_id= pk)
        form = self.form_class(instance = team_detail)
        team_tournament = Team.objects.filter(tournaments__id = 2)
        tourn = Tournament.objects.all()
        print(f"tournaments: {team_tournament}")
        # form.fields['deptName'].required = False
        return render(request, self.template_name, {"form":form, "team":team_detail})

    def post(self, request, pk):
        team_detail = Team.objects.get(team_id= pk)
        form = self.form_class(request.POST, instance=team_detail)
        if form.is_valid():
            instance = form.save(commit=False)
            # instance.deptName = team_detail.deptName
            instance.save()
            form.save()

            return self.form_valid(form)
        else:
            messages.warning(request, f"An error occurred: {form.errors.as_text}")
        return redirect("auth:team")

    def get_success_url(self):
        return reverse_lazy('auth:team')

class TeamPlayers(ListView, FormView):
    model = Player
    context_object_name = "players"
    template_name = "lvs_auth/team_players.html"
    form_class = TeamPlayerForm
    # success_url = reverse_lazy("auth:team_players", id)

    def get_queryset(self):
        # qs = super().get_queryset()
        players = self.model.objects.filter(team_id = self.kwargs['pk'])
        return players

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['team_pk'] = self.kwargs['pk']
        team = Team.objects.get(team_id=context['team_pk'])
        context['team_name'] = team.deptName.deptName
        return context

    def post(self, request, pk, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        print(request.POST)
        team = Team.objects.get(team_id=pk)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.team_id = team
            instance.goals = 0
            instance.assists = 0
            instance.is_captain = False
            instance.save()
            messages.success(self.request, "Player Added to Team")

            return redirect("auth:team_players", pk)
        else:
            messages.error(self.request, f"An error occured")
            return self.form_invalid(form)

class DeletePlayer(SuccessMessageMixin, DeleteView):
    model = Player
    success_message = 'Player Deleted Successfully'
    # success_url = reverse_lazy('auth:team_players')

    def get_success_url(self):
        return reverse_lazy('auth:team_players', kwargs={'pk': self.request.POST['team_pk']} )

class UpdatePlayer(UpdateView):
    model = Player
    template_name = "lvs_auth/update_player.html"
    form_class = TeamPlayerForm

    def get(self, request, pk, *args, **kwargs):
        player_detail = Player.objects.get(id= pk)
        form = self.form_class(instance = player_detail)
        return render(request, self.template_name, {"form":form})

class UpdateMatch(SuccessMessageMixin, UpdateView):
    model = Match
    template_name = "lvs_auth/update_match.html"
    form_class = UpdateMatchForm
    success_message = "Match Updated"
    success_url = reverse_lazy('scores:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        match_id = self.kwargs['pk']
        # context["team_name"] = Match.objects.get(id = match_id)
        context["team"] = Match.objects.get(id = match_id)
        return context

    def match_time(self):
        match = Match.objects.get(fixture__match_date_time__date=datetime.date.today())
        global scheduler
        if match.status != 'not_started':
            match.time += 1
            print(f"time: {match.time}")
            match.save()
        elif match.status == 'FT':
            scheduler.remove_job('time_0001')


    # def form_valid(self, request, form):
    #     if form.is_valid():
    #         instance = form.save(commit=False)
    #         # print(f"time now: {now}")
    #         form.save()
    #         return super().form_valid(form)
    #     else:
    #         messages.warning(request, "An error occurred")
    #         return self.form_invalid(form)

# class UpdateMatchStat(SuccessMessageMixin, UpdateView):
#     model = MatchStats
#     template_name = "lvs_auth/update_match_score.html"
#     success_message = "Match Stats Successfully Updated"

#     def post()

class UpdateMatchScoreV(SuccessMessageMixin, UpdateView):
    model = Match
    template_name = "lvs_auth/update_match_score.html"
    form_class = UpdateGoalScorerForm
    second_form_class = UpdateMatchStatusForm
    third_form_class = UpdateCardBookingForm
    fourth_form_class = UpdateMatchStatForm
    fifth_form_class = AdditionalInfoForm

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)

        match_id = self.kwargs['pk']
        match = Match.objects.get(pk = match_id)
        match_stats = MatchStats.objects.update_or_create(match = match)
        print(f"match_status: {match_stats}")
        context['matchStatusForm'] = self.second_form_class(instance=match)
        context['matchStatsForm'] = self.fourth_form_class(self.request, instance=match_stats[0])
        context['additionalInfoForm'] = self.fifth_form_class()

        # instantiate forms
        goalScorerForm = self.form_class()
        cardBookingForm = self.third_form_class()
        # matchStatsForm = self.fourth_form_class(self.request, instance=match_stats[0])

        # query teams and players to be filled in select box
        homeTeam = Team.objects.filter(team_id=match.fixture.home_team.team_id)
        awayTeam = Team.objects.filter(team_id=match.fixture.away_team.team_id)

        homePlayers = Player.objects.filter(team_id=match.fixture.home_team)
        awayPlayers = Player.objects.filter(team_id=match.fixture.away_team)

        goalScorerForm.fields['team'].queryset = homeTeam | awayTeam
        goalScorerForm.fields['scorer'].queryset = homePlayers | awayPlayers
        goalScorerForm.fields['assist'].queryset = homePlayers | awayPlayers

        cardBookingForm.fields['red_card'].queryset = homePlayers | awayPlayers
        cardBookingForm.fields['yellow_card'].queryset = homePlayers | awayPlayers

        # matchStatsForm.fields['corner'].queryset = homeTeam | awayTeam

        context['goalScorerForm'] = goalScorerForm
        context['cardBookingForm'] = cardBookingForm
        context['match_time'] = match.time
        # context['matchStatsForm'] = matchStatsForm

        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        match = Match.objects.get(pk = self.kwargs['pk'])
        match_stats = MatchStats.objects.update_or_create(match = match)

templates/lvs_auth/1dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block head %}{% include 'utils/head.html' %}{% endblock head %}
{% block body %}

    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
      <div class="layout-container">
        <!-- Menu -->

        {% block aside %}{% include 'utils/aside.html' %}{% endblock aside %}
        <!-- / Menu -->

        <!-- Layout container -->
        <div class="layout-page">
          <!-- Navbar -->

          {% include 'utils/nav.html' %}

          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->

            <div class="container-xxl flex-grow-1 container-p-y">
              <div class="row">
                <div class="col-lg-12 mb-4 order-0">
                  <div class="card">
                    {% include 'utils/messages.html' %}
                    <div class="d-flex align-items-end row">
                      <div class="col-sm-7">
                        Timer
                        <div class="card-body">
                          <h3 class="card-title text-primary">Today's Match 🎉Timer: 
                          
                        </div>      
                      </div> 
                    </div>
                    <div class="container">
                        <div class="row">
                          <div class="col-md-12">

                            <div hx-get="{% url 'auth:dashboard' %}" hx-trigger="every 2s" hx-swap="innerHTML">
                              <p>HELLO</P>
                            </div>

                            {% if today_match %}
                            {% for today in today_match %}
                              {% if request.user.is_staff %} <a href=" {% if today.status == "not_started" %}{% url 'auth:update_match' today.id %} {% else %}{% url 'auth:update_match_score' today.id %}{% endif %}">  {% else %} 
                                <a href="{% url 'scores:match_summary' today.pk %}">{% endif %}
                                <div class="bg-image overlay-success rounded mb-5" style="background-image: url( {% static 'assets/img/backgrounds/bg_3.jpg' %} );" hx-get="{% url 'scores:index' %}" hx-trigger="every 2s" hx-swap="innerHTML" data-stellar-background-ratio="0.5">

                                  {% include 'utils/match_card.html' %}  
                                </div>
                              {% if request.user.is_staff %}</a> {% else %}</a> {% endif %}
                                {% endfor %}
                            {% else %}
                            <p class="text-dark text-center h3"><span class="h3">No Match Today</span></p>
                              
                            {% endif %}
                        </div>

                        {% include 'scores_fixtures/timer.html' %}
                       
                          <h4 class="card-title text-primary">Next Match</h4>
                       
                        <div class="row mb-5">
                          <div class="col-md-12">
                            <div class="border mb-3 rounded d-block d-lg-flex align-items-center p-3 next-match">
                              <div class="mr-auto order-md-1 w-60 text-center text-lg-left mb-3 mb-lg-0">
                                Date/Time
                                <div id="date-countdown"></div>
                              </div>
                
                              <div class="ml-auto pr-4 order-md-2">
                                <div class="h5 text-black text-uppercase text-center text-lg-left">
                                  <div class="d-block d-md-inline-block mb-3 mb-lg-0">
                                    <span class="d-block d-md-inline-block ml-0 ml-md-3 ml-lg-0">Home Team </span>
                                  </div>
                                  <span class="text-muted mx-3 text-normal mb-3 mb-lg-0 d-block d-md-inline ">vs</span> 
                                  <div class="d-block d-md-inline-block">
                                    <span class="d-block d-md-inline-block ml-0 ml-md-3 ml-lg-0">Away Team</span>
                                  </div>
                                </div>
                              </div>
                         
                            </div>
                          </div>
                        </div>

                        {% comment %} Fixtures {% endcomment %}
                        <div class="row">
                          <div class="col-md-12">
                
                            <h3 class="card-title text-primary">Fixtures</h3>
                          
                            <div class="site-block-tab">
                              <ul class="nav nav-pills" id="pills-tab" role="tablist">
                                <li class="nav-item">
                                  <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-rector" role="tab" aria-controls="pills-home" aria-selected="true">Rector's Cup</a>
                                </li>
                                <li class="nav-item">
                                  <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Departmental</a>
                                </li>
                              
                              </ul>
                              <div class="tab-content" id="pills-tabContent">
                                <div class="tab-pane fade show active" id="pills-rector" role="tabpanel" aria-labelledby="pills-home-tab">
                                {% if rector_fixture %}
                                  <div class="row align-items-center">
                                    <div class="col-md-12">
                                        {% for rector in rector_fixture %}
                                          <div class="row">
                                            <div class="col-md-12">
                                              <div class="border mb-3 rounded d-block d-lg-flex align-items-center p-3 next-match">
                                                <div class="mr-auto order-md-1 w-60 text-center text-lg-left mb-3 mb-lg-0">
                                                  {{rector.match_date_time}}
                                                </div>
                                  
                                                <div class="ml-auto pr-4 order-md-2">
                                                  <div class="h5 text-black text-uppercase text-center text-lg-left">
                                                    <div class="d-block d-md-inline-block mb-3 mb-lg-0">
                                                      <span class="d-block d-md-inline-block ml-0 ml-md-3 ml-lg-0">{{rector.home_team}} </span>
                                                    </div>
                                                    <span class="text-muted mx-3 text-normal mb-3 mb-lg-0 d-block d-md-inline ">vs</span> 
                                                    <div class="d-block d-md-inline-block">
                                                      <span class="d-block d-md-inline-block ml-0 ml-md-3 ml-lg-0">{{rector.away_team}}</span>
                                                    </div>
                                                  </div>
                                                </div>
                                          
                                              </div>
                                            </div>
                                          </div>
                                        {% endfor %}
                                          <!-- END row -->
                                      </div>
                                    </div>
                                  {% else %}
                                          <div class="row mb-5">
                                            <div class="col-md-12">
                                              <div class="border mb-3 rounded d-block d-lg-flex align-items-center p-3 next-match">
                                                <div class="mr-auto order-md-1 w-60 text-center text-lg-left mb-3 mb-lg-0 font-bold">
                                                  No Fixture
                                                  <div id="date-countdown"></div>
                                                </div>
                                
                                              </div>
                                            </div>
                                          </div>
                                  {% endif %}
                                </div>
                                <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
                                  
                                  {% if dept_fixture %}
                                  <div class="row align-items-center">
                                    <div class="col-md-12">
                                        {% for dept in dept_fixture %}
                                          <div class="row">
                                            <div class="col-md-12">
                                              <div class="border mb-3 rounded d-block d-lg-flex align-items-center p-3 next-match">
                                                <div class="mr-auto order-md-1 w-60 text-center text-lg-left mb-3 mb-lg-0">
                                                  {{dept.match_date_time}}
                                                  <div id="date-countdown"></div>
                                                </div>
                                  
                                                <div class="ml-auto pr-4 order-md-2">
                                                  <div class="h5 text-black text-uppercase text-center text-lg-left">
                                                    <div class="d-block d-md-inline-block mb-3 mb-lg-0">
                                                      <span class="d-block d-md-inline-block ml-0 ml-md-3 ml-lg-0">{{dept.home_team}} </span>
                                                    </div>
                                                    <span class="text-muted mx-3 text-normal mb-3 mb-lg-0 d-block d-md-inline ">vs</span> 
                                                    <div class="d-block d-md-inline-block">
                                                      <span class="d-block d-md-inline-block ml-0 ml-md-3 ml-lg-0">{{dept.away_team}}</span>
                                                    </div>
                                                  </div>
                                                </div>
                                          
                                              </div>
                                            </div>
                                          </div>
                                        {% endfor %}
                                          <!-- END row -->
                                      </div>
                                    </div>
                                  {% else %}
                                          <div class="row mb-5">
                                            <div class="col-md-12">
                                              <div class="border mb-3 rounded d-block d-lg-flex align-items-center p-3 next-match">
                                                <div class="mr-auto order-md-1 w-60 text-center text-lg-left mb-3 mb-lg-0">
                                                  No Fixture
                                                  <div id="date-countdown"></div>
                                                </div>
                                
                                              </div>
                                            </div>
                                          </div>
                                  {% endif %}
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>

                  </div>

                </div>
                
                </div>
            </div>
            <!-- / Content -->

            <!-- Footer -->
            {% include 'utils/footer.html' %}

            <!-- / Footer -->

            <div class="content-backdrop fade"></div>
          </div>
          <!-- Content wrapper -->
        </div>
        <!-- / Layout page -->
      </div>

   
    </div>
    <!-- / Layout wrapper -->
    {% include 'utils/scripts.html' %}

   
  
{% endblock body %}

templates/lvs_auth/teams.html
{% extends 'base.html' %}
{% load static %}
{% block head %}{% include 'utils/auth_head.html' %}{% endblock head %}
{% block title %}Teams{% endblock title %}
{% block body %}

    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
      <div class="layout-container">
        <!-- Menu -->

        {% block aside %}{% include 'utils/aside.html' %}{% endblock aside %}
        <!-- / Menu -->

        <!-- Layout container -->
        <div class="layout-page">
          <!-- Navbar -->

          {% include 'utils/nav.html' %}

          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->

            <div class="container-xxl flex-grow-1 container-p-y">
              <div class="row">
                <div class="col-lg-12 mb-4 order-0">
                  <div class="card">
                    <div class="d-flex align-items-end row">
                      <div class="col-sm-7">
                        <div class="card-body">
                          <h3 class="card-title text-primary">Manage Teams</h3>
                        </div>      
                      </div> 
                    </div>
                    <div class="container">
                      {% include 'utils/messages.html' %}
                      <div class="row mb-4 justify-content-end">
                        <div class="col-md-4 ml-auto mb-4">
                          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalSamp">Add Team</button>
                          {% include 'utils/team_modal.html' %}
                        </div>
                      </div>
                        <div class="row mb-5">
                          <div class="col-md-12">
                            {% if teams %}
                            <table class="table table-bordered table-striped">
                              <tr>
                                  <th>NAME</th>
                                  <th>COACH</th>
                                  <th>ACTION</th>                
                              </tr>
                              {% for team in teams %}
                                             
                                  <tr>
                                      <td>{{team.deptName}}</a></td>
                                      <td>{{team.coach}}</td>
                                      <td>
                                          <a href="{% url 'auth:team_players' team.team_id %}" class="btn btn-primary">PLAYERS</a>
                                          <a href="{% url 'auth:update_team' team.pk %}" class="btn btn-warning"><i class="menu-icon tf-icons bx bxs-pencil"></i></a>
                                          <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete{{forloop.counter}}"><i class="menu-icon tf-icons bx bxs-trash"></i></button>
                                          
                                          <div id="delete{{forloop.counter}}" class="modal fade" role="dialog">
                                            <div class="modal-dialog">
                                          
                                              <!-- Modal content-->
                                              <div class="modal-content">
                                                <div class="modal-header">
                                                    <h4 class="modal-title">Delete Team</h4>
                                                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                </div>
                                                <hr/>
                                                <div class="modal-body">
                                                  <form action="{% url 'auth:delete_team' team.pk  %}" method="post">
                                                    {% csrf_token %}
                                                      
                                                      <div class="row mb-3">
                                                        <h5>Are you sure you want to delete {{team.deptName}}?, <span class="text-warning"> All Matches played by this will also be deleted. </span> </h4>
                                                      </div>
                                                        <hr/>
                                                        <div class="modal-footer">
                                                          <button type="submit" class="btn btn-danger">Submit</button>
                                                        </div>
                                                  </form>
                                                </div>
                                              </div>
                                          
                                            </div>
                                          </div>

                                      </td>  
                                  </tr>
                              {% endfor %}
                          </table>
                            {% else %}
                            <div class="col text-center">
                              <h4 class="">No record of teams</h4>
                            </div>
                            {% endif %}
                          </div>
                        </div>
                        
                      </div>

                  </div>

                  
                </div>
                
                

                </div>
            </div>
            <!-- / Content -->

            <!-- Footer -->
            {% include 'utils/footer.html' %}

            <!-- / Footer -->

            <div class="content-backdrop fade"></div>
          </div>
          <!-- Content wrapper -->
        </div>
        <!-- / Layout page -->
      </div>

   
    </div>
    <!-- / Layout wrapper -->
    {% include 'utils/scripts.html' %}
   
  
{% endblock body %}