Kad_LVS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scores_fixtures.urls')),
    path('auth/', include('lvs_auth.urls')),
   
    path('tournament/', include('tournament.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

scores_fixtures/urls.py
from django.urls import path
from .views import (HomeViewL, FixturesView, 
                    DeleteFixtureView, UpdateFixtureView,
                    MatchesView, MatchSummary)

app_name = 'scores'
urlpatterns = [
    # path('', HomeView.as_view(), name='index'),
    path('', HomeViewL.as_view(), name='index'),
    path('fixtures/<str:template_name>/', FixturesView.as_view(), name='fixtures'),
    path('fixtures/<str:template_name>/update/<int:pk>/',UpdateFixtureView.as_view(), name='update_fixture'),
    path('fixtures/<str:template_name>/delete/<int:pk>/', DeleteFixtureView.as_view(), name='delete_fixture'),
    path('matches/<str:template_name>/', MatchesView.as_view(), name='matches'),
    path('matches/summary/<int:pk>/', MatchSummary.as_view(), name='match_summary'),
]

scores_fixtures/models.py
from django.db import models

from tournament.models import Tournament, Team, Player
# Create your models here.

match_status = [
    ("not_started", "not_started"),
    ("ON", "ON"),
    ("HT", "HT"),
    ("FT", "FT"),
    ("ET", "ET"),
    ("postponed", "postponed"),
]

class Fixture(models.Model):
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    home_team = models.ForeignKey(Team, related_name='home_team', on_delete=models.CASCADE)
    away_team = models.ForeignKey(Team, related_name='away_team', on_delete=models.CASCADE)
    match_date_time = models.DateTimeField()

    def __str__(self):
        return "{0} vs {1}".format(self.home_team, self.away_team)

class Match(models.Model):
    fixture = models.ForeignKey(Fixture, on_delete=models.CASCADE)
    home_team_score = models.IntegerField(default=0, blank=True, null=True,)
    away_team_score = models.IntegerField(default=0, blank=True, null=True,)
    home_team_formation = models.CharField(max_length=10, default="4-4-2")
    away_team_formation = models.CharField(max_length=10, default="4-4-2")
    referee = models.CharField(max_length=30)
    status = models.CharField(max_length=15, choices=match_status, default="not_started")
    time = models.IntegerField(default=0)
    
    class Meta:
        verbose_name_plural = "Matches"
    def __str__(self):
        return "{0} vs {1}".format(self.fixture.home_team, self.fixture.away_team)

class GoalScorers(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    time = models.IntegerField(default=0)
    scorer = models.ForeignKey(Player, related_name='home_scorer', blank=True, null=True, on_delete=models.CASCADE)
    assist = models.ForeignKey(Player, related_name='home_assist', blank=True, null=True, on_delete=models.CASCADE)
    home_score = models.IntegerField(default=0, null=True, blank=True)
    away_score = models.IntegerField(default=0, null=True, blank=True)

    class Meta:
        verbose_name_plural = "Goal Scorers"
    def __str__(self):
        return f"""Match: {self.match.fixture.home_team.deptName.deptName} - {self.match.fixture.away_team.deptName.deptName}
                    """
    
class Card(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    time = models.IntegerField(default=0)
    red_card = models.ForeignKey(Player, related_name='red_card', on_delete=models.CASCADE, null=True, blank=True)
    yellow_card = models.ForeignKey(Player, related_name='yellow_card', on_delete=models.CASCADE, null=True, blank=True)

class MatchStats(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    home_corner = models.IntegerField(default=0)
    away_corner = models.IntegerField(default=0)
    home_fouls = models.IntegerField(default=0)
    away_fouls = models.IntegerField(default=0)
    home_ball_possession = models.IntegerField(default=0)
    away_ball_possession = models.IntegerField(default=0)
    home_offside = models.IntegerField(default=0)
    away_offside = models.IntegerField(default=0)

class MatchAdditionalInfo(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    time = models.IntegerField(default=0)
    additional_info = models.CharField(max_length=1000, null=True, blank=True)

    



    

scores_fixtures/forms.py
from django import forms

from . models import Fixture, Tournament, Team

class FixturesForm(forms.ModelForm):

  
    home_team = forms.ModelChoiceField(queryset=Team.objects.none(), empty_label="Select Home Team", required=True, widget=forms.Select(
        attrs={
            'class':'form-control select form-select',
        }
    ))
    
    away_team = forms.ModelChoiceField(queryset=Team.objects.none(), empty_label="Select Away Team", required=True, widget=forms.Select(
        attrs={
            'class':'form-control select form-select',
        }
    ))

    class Meta:
        model = Fixture
        fields = "__all__"

        widgets = {
            "match_date_time": forms.DateTimeInput(
                attrs={
                    'class': 'form-control',
                    'type': 'datetime-local'
                }
            )
        }
    
    # def __init__(self, *args, **kwargs):
    #     template_name = kwargs.pop('template_name', None)
    #     super(FixturesForm, self).__init__(*args, **kwargs)

    #     if template_name == "rector_cup":
    #         tournament = Tournament.objects.get(name="rector_cup")
    #         self.fields['home_team'].queryset = Team.objects.filter(tournaments = tournament)
    #         self.fields['away_team'].queryset = Team.objects.filter(tournaments = tournament)
    #     elif template_name == "departmental":
    #         tournament = Tournament.objects.get(name="departmental")
    #         self.fields['home_team'].queryset = Team.objects.filter(tournaments = tournament)
    #         self.fields['away_team'].queryset = Team.objects.filter(tournaments = tournament)

scores_fixtures/views.py
from datetime import date
from itertools import chain
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import (ListView, FormView, TemplateView,
                                   View, UpdateView, DeleteView)
from django.shortcuts import render, redirect

from . forms import FixturesForm
from . models import Fixture, Tournament, Team, Match, GoalScorers, Card, MatchStats, MatchAdditionalInfo
# Create your views here.

class HomeViewL(View):
    def get(self, request):
        context = {}
        current_date = date.today()
        fixture_date = Fixture.objects.filter(match_date_time__date=current_date)
        print(f"path: {request.path}")
        context['today_match'] = Match.objects.filter(fixture__in=fixture_date)
        context['next_match'] = Match.objects.filter(fixture__match_date_time__date__gt=current_date).first()

        context["rector_fixture"] = Fixture.objects.filter(tournament__name="rector_cup")
        context["dept_fixture"] = Fixture.objects.filter(tournament__name="departmental")
        context['ended'] = Match.objects.filter(status__in=['postponed', 'FT'])

        # match time
        try:
            match = Match.objects.get(fixture__match_date_time__date=current_date)
            context['match_time'] = match.time
        except Match.DoesNotExist:
            return render(request, "scores_fixtures/index.html", context=context)

        # print(f"id: {match.id}")

        if request.htmx:
            return render(request, "utils/match_card.html", context)
        else:
            return render(request, "scores_fixtures/index.html", context=context)


# def HomeViewL(request):
#     context = {}
#     current_date = datetime.date.today()
#     fixture_date = Fixture.objects.filter(match_date_time__date = current_date)
#     print(f"path: {request.path}")
#     context['today_match'] = Match.objects.filter(fixture__in=fixture_date)
#     context['next_match'] = Match.objects.filter(fixture__match_date_time__date__gt=current_date).first()

#     context["rector_fixture"] = Fixture.objects.filter(tournament__name = "rector_cup")
#     context["dept_fixture"] = Fixture.objects.filter(tournament__name = "departmental")
#     context['ended'] = Match.objects.filter(status__in = ['postponed', 'FT'])

#     # match time
#     match = Match.objects.get(fixture__match_date_time__date = current_date)
#     context['match_time'] = match.time

#     print(f"id: {match.id}")

#     if request.htmx:
#         return render(request, "utils/match_card.html", context)
#     else:
#         return render(request, "scores_fixtures/index.html", context=context)

# class HomeView(ListView):
#     model = Fixture
#     context_object_name = "matches"
#     template_name = "scores_fixtures/index.html"
#     # current_date = timezone.now().date()
#     current_date = datetime.date.today()
#     # print(f"current date: {current_date}")

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         fixture_date = Fixture.objects.filter(match_date_time__date = self.current_date)

#         context['today_match'] = Match.objects.filter(fixture__in=fixture_date)
#         # context['home_team'] =
#         context["rector_fixture"] = Fixture.objects.filter(tournament__name = "rector_cup")
#         context["dept_fixture"] = Fixture.objects.filter(tournament__name = "departmental")
#         return context

# class UpdateMatchTime(UpdateView):
#     model =
class FixturesView(LoginRequiredMixin, SuccessMessageMixin, TemplateView, ListView, FormView):
    login_url = "auth:login"
    model = Fixture
    context_object_name = "rector"
    template_name = "scores_fixtures/rector_fixtures.html"
    object_list = Fixture.objects.all()
    success_message = "Fixtures Added"

    form_class = FixturesForm
    # success_url = reverse_lazy("auth:team_players", id)

    def get_template_names(self):
        template_name = self.kwargs.get('template_name')
        if template_name == 'rector-cup':
            return ["scores_fixtures/rector_fixtures.html"]
        elif template_name == 'departmental':
            return ["scores_fixtures/departmental_fixtures.html"]
        else:
            return ["utils/404.html"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # load form
        form = self.form_class()
        form.fields['tournament'].required = False
        template_name = self.kwargs['template_name']
        if template_name == "rector-cup":
            tournament = Tournament.objects.get(name="rector_cup")
            # print(f"tournament: {tournament}")
            form.fields['home_team'].queryset = Team.objects.filter(tournaments = tournament)
            form.fields['away_team'].queryset = Team.objects.filter(tournaments = tournament)
            # print("fixed")
        elif template_name == "departmental":
            tournament = Tournament.objects.get(name="departmental")
            form.fields['home_team'].queryset = Team.objects.filter(tournaments = tournament)
            form.fields['away_team'].queryset = Team.objects.filter(tournaments = tournament)

        # add to context based on the template_name
        if self.kwargs['template_name'] == "rector-cup":
            context["rector_fixture"] = Fixture.objects.filter(tournament__name = "rector_cup")
        elif self.kwargs['template_name'] == "departmental":
            context["dept_fixture"] = Fixture.objects.filter(tournament__name = "departmental")

        # add form and template_name to context
        context['form'] = form
        context['template_name'] = template_name
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)

        form = self.form_class(request.POST)
        form.fields['tournament'].required = False
        template_name = self.kwargs['template_name']
        print(f"template: {template_name}")
        if template_name == "rector-cup":
            tournament = Tournament.objects.get(name="rector_cup")
            form.fields['home_team'].queryset = Team.objects.filter(tournaments = tournament)
            form.fields['away_team'].queryset = Team.objects.filter(tournaments = tournament)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.home_team = form.cleaned_data['home_team']
                instance.away_team = form.cleaned_data['away_team']
                instance.match_date_time = form.cleaned_data['match_date_time']

                if instance.home_team == instance.away_team:
                    messages.warning(request, "Both teams should be different")
                    return redirect("scores:fixtures", self.kwargs['template_name'])

                 # compare supplied date
                if instance.match_date_time.__lt__(timezone.now()):
                    messages.warning(request, "Older dates can't be supplied")
                    return redirect("scores:fixtures", self.kwargs['template_name'])

                # check if form already exist
                fixture = Fixture.objects.filter(match_date_time = instance.match_date_time).exists()
                if fixture:
                    messages.warning(request, "Fixture Present Already, Kindly check the form")
                    return redirect("scores:fixtures", self.kwargs['template_name'])


                instance.tournament = tournament
                instance.save()
                Match.objects.create(
                 fixture = instance
                )

                return redirect("scores:fixtures", self.kwargs['template_name'])
            else:
                messages.error(request, f"An error occurred: {form.errors.as_text}")
        elif template_name == "departmental":
            tournament = Tournament.objects.get(name="departmental")
            form.fields['home_team'].queryset = Team.objects.filter(tournaments = tournament)
            form.fields['away_team'].queryset = Team.objects.filter(tournaments = tournament)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.home_team = form.cleaned_data['home_team']
                instance.away_team = form.cleaned_data['away_team']
                instance.match_date_time = form.cleaned_data['match_date_time']

                if instance.home_team == instance.away_team:
                    messages.warning(request, "Both teams should be different")
                    return redirect("scores:fixtures", self.kwargs['template_name'])

                 # compare supplied date
                if instance.match_date_time.__lt__(timezone.now()):
                    messages.warning(request, "Older dates can't be supplied")
                    return redirect("scores:fixtures", self.kwargs['template_name'])

                instance.tournament = tournament
                instance.save()
                Match.objects.create(
                 fixture = instance
                )

                return redirect("scores:fixtures", self.kwargs['template_name'])
            else:
                messages.error(request, f"An error occurred: {form.errors.as_text}")
        else:
            messages.error(request, f"An error occured: {form.errors.as_text}")
            return redirect("scores:fixtures", self.kwargs['template_name'])

        return self.render_to_response(context)

class UpdateFixtureView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    login_url = "auth:login"
    model = Fixture

templates/scores_fixtures/departmental_fixtures.html
{% extends 'base.html' %}
{% load static %}
{% block head %}{% include 'utils/auth_head.html' %}

{% endblock head %}
{% block body %}

    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
      <div class="layout-container">
        <!-- Menu -->

        {% block aside %}{% include 'utils/aside.html' %}{% endblock aside %}
        <!-- / Menu -->

        <!-- Layout container -->
        <div class="layout-page">
          <!-- Navbar -->

          {% include 'utils/nav.html' %}

          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->

            <div class="container-xxl flex-grow-1 container-p-y">
              <div class="row">
                <div class="col-lg-12 mb-4 order-0">
                  <div class="card">
                    <div class="d-flex align-items-end row">
                      <div class="col-sm-7">
                        <div class="card-body">
                          <h3 class="card-title text-primary">Manage Departmental Cup Fixture</h3>
                        </div>      
                      </div> 
                    </div>
                    <div class="container">
                      {% include 'utils/messages.html' %}
                      <div class="row mb-4 justify-content-end">
                        <div class="col-md-4 ml-auto">
                          {% comment %} <a href="{% url 'scores:fixtures' 'add_fixture' %}" class="btn btn-primary" data-toggle="modal" data-target="#modalSamp">Add Fixture</a> {% endcomment %}
                          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalSamp"><i class="menu-icon tf-icons bx bx-table"></i>Add Fixture</button>
                          {% include 'scores_fixtures/fixtures_modal.html' %}
                        </div>
                      </div>
                        <div class="row mb-5">
                          <div class="col-md-12">
                            {% if dept_fixture %}
                            <table class="table table-bordered table-striped">
                              <tr>
                                <th>NAME</th>
                                <th>DATE AND TIME</th>
                                <th>ACTION</th> 
                              </tr>
                              {% for dept in dept_fixture %}
                                <tr>
                                  <td>
                                    {{dept.home_team}} vs {{dept.away_team}}
                                  </td>
                                  <td>{{dept.match_date_time}}</td>
                                  <td>
                                    <a href="{% url 'scores:update_fixture' template_name dept.id %}" class="btn btn-warning"><i class="menu-icon tf-icons bx bxs-pencil"></i></a>
                                    
                                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete{{forloop.counter}}"><i class="menu-icon tf-icons bx bxs-trash"></i></button>
                                    
                                    <div id="delete{{forloop.counter}}" class="modal fade" role="dialog">
                                      <div class="modal-dialog">
                                    
                                        <!-- Modal content-->
                                        <div class="modal-content">
                                          <div class="modal-header">
                                              <h4 class="modal-title">Delete Fixture</h4>
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                          </div>
                                          <hr/>
                                          <div class="modal-body">
                                            <form action="{% url 'scores:delete_fixture' template_name dept.id  %}" method="post">
                                              {% csrf_token %}     
                                                <div class="row mb-3">
                                                  <h5>Are you sure you want to delete this fixture?</h4>
                                                    <input type="hidden" value="{{template_name}}" name="template_name">
                                                </div>
                                                  <hr/>
                                                  <div class="modal-footer">
                                                    <button type="submit" class="btn btn-danger">Submit</button>
                                                  </div>
                                            </form>
                                          </div>
                                        </div>
                                    
                                      </div>
                                    </div>

                                  </td>
                                </tr>
                              {% endfor %}
                              </table>
                            {% else %}
                            <div class="col text-center">
                              <h4 class="">NO FIXTURES FOR THE DEPARTMENTAL CUP</h4>
                          </div>
                            {% endif %}
                          </div>
                        </div>
                        
                      </div>
                  </div>
                </div>
                </div>
            </div>
            <!-- / Content -->

            <!-- Footer -->
            {% include 'utils/footer.html' %}

            <!-- / Footer -->

            <div class="content-backdrop fade"></div>
          </div>
          <!-- Content wrapper -->
        </div>
        <!-- / Layout page -->
      </div>

   
    </div>
    <!-- / Layout wrapper -->
    {% include 'utils/scripts.html' %}
  
{% endblock body %}

templates/scores_fixtures/fixtures_modal.html
<div id="modalSamp" class="modal fade" role="dialog">
    <div class="modal-dialog">
  
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Add Fixture</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <hr/>
        <div class="modal-body">
          <form method="post">
            {% csrf_token %}
                
              <div class="row mb-3">
                {% if form.home_team.errors %}
                  <div class="alert alert-danger mt-2" role="alert">
                    {{ form.home_team.errors }}
                  </div>
                {% endif %}
                <label class="col-sm-2 col-form-label" for="basic-default-name">Home</label>
                <div class="col-sm-10">
                    {{form.home_team}}
                </div>
                
              </div>
              
              <div class="row mb-3">
                {% if form.away_team.errors %}
                  <div class="alert alert-danger mt-2" role="alert">
                    {{ form.away_team.errors }}
                  </div>
                {% endif %}
                <label class="col-sm-2 col-form-label" for="basic-default-name">Away</label>
                <div class="col-sm-10">
                    {{form.away_team}}
                </div>
                
              </div>

              <div class="row mb-3">
                {% if form.match_date_time.errors %}
                  <div class="alert alert-danger mt-2" role="alert">
                    {{ form.match_date_time.errors }}
                  </div>
                {% endif %}
                <label class="col-sm-2 col-form-label" for="basic-default-name">Match Date and Time</label>
                <div class="col-sm-10">
                    {{form.match_date_time}}
                </div>
                
              </div>

                <hr/>
                <div class="modal-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
          </form>
        </div>
      </div>
  
    </div>
  </div>

templates/scores_fixtures/rector_fixtures.html
{% extends 'base.html' %}
{% load static %}
{% block head %}{% include 'utils/auth_head.html' %}

{% endblock head %}
{% block body %}

    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
      <div class="layout-container">
        <!-- Menu -->

        {% block aside %}{% include 'utils/aside.html' %}{% endblock aside %}
        <!-- / Menu -->

        <!-- Layout container -->
        <div class="layout-page">
          <!-- Navbar -->

          {% include 'utils/nav.html' %}

          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->

            <div class="container-xxl flex-grow-1 container-p-y">
              <div class="row">
                <div class="col-lg-12 mb-4 order-0">
                  <div class="card">
                    <div class="d-flex align-items-end row">
                      <div class="col-sm-7">
                        <div class="card-body">
                          <h3 class="card-title text-primary">Manage Rector's Cup Fixture</h3>
                        </div>      
                      </div> 
                    </div>
                    <div class="container">
                      {% include 'utils/messages.html' %}
                      <div class="row mb-4 justify-content-end">
                        <div class="col-md-4 ml-auto">
                          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalSamp"><i class="menu-icon tf-icons bx bx-table"></i>Add Fixture</button>
                          {% include 'scores_fixtures/fixtures_modal.html' %}
                        </div>
                      </div>
                        <div class="row mb-5">
                          <div class="col-md-12">
                            {% if rector_fixture %}
                            <table class="table table-bordered table-striped">
                              <tr>
                                <th>NAME</th>
                                <th>DATE AND TIME</th>
                                <th>ACTION</th> 
                              </tr>
                              {% for rector in rector_fixture %}
                                <tr>
                                  <td>
                                    {{rector.home_team}} vs {{rector.away_team}}
                                  </td>
                                  <td>{{rector.match_date_time}}</td>
                                  <td>
                                    <a href="{% url 'scores:update_fixture' template_name rector.id %}" class="btn btn-warning"><i class="menu-icon tf-icons bx bxs-pencil"></i></a>
                                    
                                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete{{forloop.counter}}"><i class="menu-icon tf-icons bx bxs-trash"></i></button>
                                    
                                    <div id="delete{{forloop.counter}}" class="modal fade" role="dialog">
                                      <div class="modal-dialog">
                                    
                                        <!-- Modal content-->
                                        <div class="modal-content">
                                          <div class="modal-header">
                                              <h4 class="modal-title">Delete Fixture</h4>
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                          </div>
                                          <hr/>
                                          <div class="modal-body">
                                            <form action="{% url 'scores:delete_fixture' template_name rector.id  %}" method="post">
                                              {% csrf_token %}     
                                                <div class="row mb-3">
                                                  <h5>Are you sure you want to delete this fixture? <span class="text-warning"> All Matches played by these teams will also be deleted. </span> </h4>
                                                    <input type="hidden" value="{{template_name}}" name="template_name">
                                                </div>
                                                  <hr/>
                                                  <div class="modal-footer">
                                                    <button type="submit" class="btn btn-danger">Submit</button>
                                                  </div>
                                            </form>
                                          </div>
                                        </div>
                                    
                                      </div>
                                    </div>

                                  </td>
                                </tr>
                              {% endfor %}
                              </table>
                            {% else %}
                            <div class="col text-center">
                              <h4 class="">No FIXTURES FOR THE RECTOR'S CUP</h4>
                          </div>
                            {% endif %}
                          </div>
                        </div>
                        
                      </div>
                  </div>
                </div>
                </div>
            </div>
            <!-- / Content -->

            <!-- Footer -->
            {% include 'utils/footer.html' %}

            <!-- / Footer -->

            <div class="content-backdrop fade"></div>
          </div>
          <!-- Content wrapper -->
        </div>
        <!-- / Layout page -->
      </div>

   
    </div>
    <!-- / Layout wrapper -->
    {% include 'utils/scripts.html' %}
  
{% endblock body %}