Kad_LVS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scores_fixtures.urls')),
    path('auth/', include('lvs_auth.urls')),
   
    path('tournament/', include('tournament.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

lvs_auth/urls.py
from django.urls import path
from . views import (LoginView, DashboardView,TeamsView, 
                     TeamPlayers, DeleteTeam, UpdateMatchScoreV, UpdateTeam, 
                      DeletePlayer, UpdatePlayer, 
                      UpdateMatch)


app_name = 'auth'
urlpatterns = [
    path('login/', LoginView.as_view(), name="login"),
    path('dashboard/', DashboardView.as_view(), name="dashboard"),
    path('teams/', TeamsView.as_view(), name='team'),
    path('teams/<str:pk>/update/', UpdateTeam.as_view(), name='update_team'),
    path('teams/<str:pk>/delete/', DeleteTeam.as_view(), name='delete_team'),
    # path('add-team/', TeamFormView.as_view(), name='team_form'),
    path('<str:pk>/players/', TeamPlayers.as_view(), name='team_players'),
    # path('players/<int:pk>/update/', updatePlayer(), name='update_player'),
    path('players/<int:pk>/update/', UpdatePlayer.as_view(), name='update_player'),
    path('players/<int:pk>/delete/', DeletePlayer.as_view(), name='delete_player'),

    path('match/<int:pk>/update/', UpdateMatch.as_view(), name="update_match"),
    path('score/<int:pk>/update/', UpdateMatchScoreV.as_view(), name="update_match_score")
]

scores_fixtures/urls.py
from django.urls import path
from .views import (HomeViewL, FixturesView, 
                    DeleteFixtureView, UpdateFixtureView,
                    MatchesView, MatchSummary)

app_name = 'scores'
urlpatterns = [
    # path('', HomeView.as_view(), name='index'),
    path('', HomeViewL.as_view(), name='index'),
    path('fixtures/<str:template_name>/', FixturesView.as_view(), name='fixtures'),
    path('fixtures/<str:template_name>/update/<int:pk>/',UpdateFixtureView.as_view(), name='update_fixture'),
    path('fixtures/<str:template_name>/delete/<int:pk>/', DeleteFixtureView.as_view(), name='delete_fixture'),
    path('matches/<str:template_name>/', MatchesView.as_view(), name='matches'),
    path('matches/summary/<int:pk>/', MatchSummary.as_view(), name='match_summary'),
]

templates/utils/aside.html
{% block aside %}
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
    <div class="app-brand demo">
      <a href="{% url 'scores:index' %}" class="app-brand-link">
        <span class="app-brand-text demo menu-text fw-bolder ms-2">Kadpoly Livescore</span>
      </a>

      <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
        <i class="bx bx-chevron-left bx-sm align-middle"></i>
      </a>
    </div>

    <div class="menu-inner-shadow"></div>

    <ul class="menu-inner py-1">
      <!-- Dashboard -->
      
      {% if request.user.is_staff %}
        <li class="menu-item {% if request.path == "/" %}active{% endif %}">
          <a href="{% url 'scores:index' %}" class="menu-link">
            <i class="menu-icon tf-icons bx bx-home-circle"></i>
            <div data-i18n="Analytics">Dashboard</div>
          </a>
        </li>
      
        <li class="menu-header small text-uppercase"><span class="menu-header-text">Admin Fixtures</span></li>

        <li class="menu-item {% if 'fixtures' in request.path %}active{% endif %}">
          <a href="javascript:void(0)" class="menu-link menu-toggle">
            <i class="menu-icon tf-icons bx bx-table"></i>
            <div data-i18n="Extended UI">Manage Fixtures</div>
          </a>
          <ul class="menu-sub">
            <li class="menu-item">
              <a href="{% url 'scores:fixtures' 'rector-cup' %}" class="menu-link">
                <div data-i18n="Perfect Scrollbar">Rector's Cup </div>
              </a>
            </li>
            <li class="menu-item">
              <a href="{% url 'scores:fixtures' 'departmental' %}" class="menu-link">
                <div data-i18n="Text Divider">Departmental</div>
              </a>
            </li>
          </ul>
        </li>

        <li class="menu-item {% if request.path == '/auth/teams/' or 'players' in request.path %} active{% endif %}">
          <a href="{% url 'auth:team' %}" class="menu-link">
            <i class="menu-icon tf-icons bx bx-group"></i>
            <div data-i18n="Analytics">Manage Teams</div>
          </a>
        </li>
      {% else %}
        <li class="menu-item {% if request.path == "/" %}active {% endif %}">
          <a href="{% url 'scores:index' %}" class="menu-link">
            <i class="menu-icon tf-icons bx bx-home-circle"></i>
            <div data-i18n="Analytics">Dashboard</div>
          </a>
        </li>

      <li class="menu-header small text-uppercase">
        <span class="menu-header-text">Matches</span>
      </li>

      <li class="menu-item {% if request.path == "/matches/rector-cup/" %}active{% endif %}">
        <a href="{% url 'scores:matches' 'rector-cup' %}" class="menu-link">
          <i class="menu-icon tf-icons bx bx-medal"></i>
          <div data-i18n="Analytics">Rector's Cup</div>
        </a>
      </li>
      <li class="menu-item {% if request.path == "/matches/departmental/" %}active{% endif %}">
        <a href="{% url 'scores:matches' 'departmental' %}" class="menu-link">
          <i class="menu-icon tf-icons bx bx-medal"></i>
          <div data-i18n="Analytics">Departmental</div>
        </a>
      </li>
      {% endif %} 
    </ul>
  </aside>
{% endblock %}

templates/utils/auth_head.html
{% load static %}
<link rel="stylesheet"  href="{% static 'assets/css/bootstrap.min.css' %} " />
<link rel ="stylesheet" href = "{% static 'assets/vendor/css/core.css' %}" class="template-customizer-core-css">
<link rel ="stylesheet" href = "{% static 'assets/vendor/css/theme-default.css' %}" class="template-customizer-core-css">
<link rel="stylesheet"  href="{% static 'assets/css/style.css' %} " />
<link rel="stylesheet"  href="{% static 'assets/vendor/fonts/boxicons.css' %}" />

templates/utils/footer.html
<footer class="content-footer footer bg-footer-theme">
    <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
      <div class="mb-2 mb-md-0">
        ©
        <script>
          document.write(new Date().getFullYear());
        </script>
        , made with ❤️ by
        <a href="https://twitter.com/_ademola_b" target="_blank" class="footer-link fw-bolder">Demolab</a>
      </div>

    </div>
</footer>

templates/utils/head.html
{% load static %}

<link rel="stylesheet"  href="{% static 'assets/css/bootstrap.min.css' %}" />
<link rel="stylesheet" href="{% static 'assets/vendor/css/core.css' %}" />
<link rel="stylesheet" href="{% static 'assets/vendor/css/theme-default.css' %} " />
<link rel="stylesheet"  href="{% static 'assets/css/style.css' %} " />
<link rel="stylesheet"  href="{% static 'assets/css/demo.css' %} " />
<link rel="stylesheet"  href="{% static 'assets/vendor/fonts/boxicons.css' %}" />

templates/utils/match_card.html
{% load static %}
{% for today in today_match %}
{% if today.status == "postponed" or today.status == "FT" or today.status == "not_started" %}
<div>
    {% else %}
        <div hx-get="{% url 'scores:index' %}" hx-trigger="every 5s" hx-swap="innerHTML"> 
    {% endif %}
    {% if request.user.is_staff %} 
        <a href=" {% if today.status == "not_started" %}{% url 'auth:update_match' today.id %} {% elif today.status == "FT" %} {% url 'scores:match_summary' today.pk %} {% else %}{% url 'auth:update_match_score' today.id %}{% endif %}"> 
        
        {% else %} 
            <a href="{% url 'scores:match_summary' today.pk %}">
        {% endif %}
    
        <div class="bg-image overlay-success rounded mb-5" style="background-image: url( {% static 'assets/img/backgrounds/bg_3.jpg' %} );"  data-stellar-background-ratio="0.5">
            <div class="row align-items-center">
                <div class="col-md-12 col-lg-4 mb-4 mb-lg-0">
            
                    <div class="text-center text-lg-left">
                    <div class="d-block d-lg-flex align-items-center">
                        <div class="image mx-auto mb-3 mb-lg-0 mr-lg-3">
                        </div>
                        <div class="text">
                        <h3 class="h5 mb-0 text-black">{{today.fixture.home_team}}</h3>
                        </div>
                    </div>
                    </div>
            
                </div>
                <div class="col-md-12 col-lg-4 text-center mb-4 mb-lg-0">
                    <div class="d-inline-block">
                    <p class="mb-2"><small class="text-uppercase text-black font-weight-bold">{{today.fixture.tournament}}</small></p>
                    <div class="bg-black py-2 px-4 mb-2 text-white d-inline-block rounded"><span class="h3">{{today.home_team_score}}:{{today.away_team_score}}</span></div>
                    <p class="mb-0">
                        <span class="text-uppercase text-black font-weight-bold">
                            {% if today.status == "not_started" %}
                                {{today.fixture.match_date_time.time}}
                            {% elif today.status == 'FT' or today.status == 'HT' %}
                                {{today.status}}
                            {% elif today.status == 'ON' %}
                                <h4><span id="timer" class="text-danger">{{match_time}}'</span></h4>
                            {% endif %}
                        </span>
                    </p>
                    </div>
                </div>
            
                <div class="col-md-12 col-lg-4 text-center text-lg-right">
                    <div class="">
                    <div class="d-block d-lg-flex align-items-center">
            
                        <div class="text order-1">
                        <h3 class="h5 mb-0 text-black">{{today.fixture.away_team}}</h3>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
            {% comment %} {% include 'utils/match_card.html' %}   {% endcomment %}
        </div>
        {% if request.user.is_staff %}</a> {% else %}</a> {% endif %}    
    </div>
{% endfor %}

templates/utils/messages.html
{% if messages %}
        {% for message in messages %}
            <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <p aria-hidden="true">&times;</p>
                </button>
            </div>
        {% endfor %}
 {% endif %}

templates/utils/nav.html
<nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-light" id="layout-navbar">
  <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
    <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
      <i class="bx bx-menu bx-sm"></i>
    </a>
  </div>
</nav>

templates/utils/player_delete_modal.html
<div id="deleteModalSamp" class="modal fade" role="dialog">
    <div class="modal-dialog">
  
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Delete Player</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <hr/>
        <div class="modal-body">
          <form action="{% url 'auth:delete_player' player.id %}" method="post">
            {% csrf_token %}
              
              <div class="row mb-3">
                <h5>Are you sure you want to delete {{player.name}}?</h4>
              </div>

                <hr/>
                <div class="modal-footer">
                  <button type="submit" class="btn btn-danger">Submit</button>
                </div>
          </form>
        </div>
      </div>
  
    </div>
  </div>

templates/utils/scripts.html
{% load static %}
{% block scripts %}
    <script src=" {% static 'assets/vendor/libs/jquery/jquery.js' %} "></script>
    <script src=" {% static 'assets/vendor/libs/popper/popper.js' %} "></script>
    <script src=" {% static 'assets/vendor/js/bootstrap.js' %} "></script>
    <script src=" {% static 'assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js' %} "></script>

    <script src=" {% static 'assets/vendor/js/menu.js'%}"></script>
    <script src=" {% static 'assets/js/main.js' %} "></script>
    <script src=" {% static "assets/js/bootstrap.min.js" %}"></script>
    <script src=" {% static "assets/js/htmx.min.js" %}"></script>
{% endblock scripts %}

templates/utils/team_modal.html
<div id="modalSamp" class="modal fade" role="dialog">
    <div class="modal-dialog">
  
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Add Team</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <hr/>
        <div class="modal-body">
          <form method="post">
            {% csrf_token %}
              <div class="row mb-3">
                {% if form.deptName.errors %}
                  <div class="alert alert-danger mt-2" role="alert">
                    {{ form.deptName.errors }}
                  </div>
                {% endif %}
                <label class="col-sm-2 col-form-label" for="basic-default-name">Department</label>
                <div class="col-sm-10">
                    {{form.deptName}}
                </div>
              </div>
              
              <div class="row mb-3">
                {% if form.coach.errors %}
                  <div class="alert alert-danger mt-2" role="alert">
                    {{ form.coach.errors }}
                  </div>
                {% endif %}
                <label class="col-sm-2 col-form-label" for="basic-default-name">COACH</label>
                <div class="col-sm-10">
                    {{form.coach}}
                </div>
              </div>

              <div class="row mb-3">
                {% if form.tournaments.errors %}
                  <div class="alert alert-danger mt-2" role="alert">
                    {{ form.tournaments.errors }}
                  </div>
                {% endif %}
                <label class="col-sm-2 col-form-label" for="basic-default-name">Tournaments</label>
                <div class="col-sm-10">
                  {% if tournaments %}
                    {{form.tournaments}}
                  {% else %}
                    <h5 style="color:red;">No tournaments</h5>
                </div>
                  {% endif %}
                
                
              </div>


                <hr/>
                <div class="modal-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
          </form>
        </div>
      </div>
  
    </div>
  </div>

templates/utils/team_player_modal.html
<div id="modalSamp" class="modal fade" role="dialog">
    <div class="modal-dialog">
  
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Add Player</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <hr/>
        <div class="modal-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
              <div class="row mb-3">
                {% if form.name.errors %}
                  <div class="alert alert-danger mt-2" role="alert">
                    {{ form.name.errors }}
                  </div>
                {% endif %}
                <label class="col-sm-2 col-form-label" for="basic-default-name">Name</label>
                <div class="col-sm-10">
                    {{form.name}}
                </div>
              </div>
              
              <div class="row mb-3">
                {% if form.image.errors %}
                  <div class="alert alert-danger mt-2" role="alert">
                    {{ form.image.errors }}
                  </div>
                {% endif %}
                <label class="col-sm-2 col-form-label" for="basic-default-name">Image</label>
                <div class="col-sm-10">
                    {{form.image}}
                </div>
              </div>
              
              <div class="row mb-3">
                {% if form.age.errors %}
                  <div class="alert alert-danger mt-2" role="alert">
                    {{ form.age.errors }}
                  </div>
                {% endif %}
                <label class="col-sm-2 col-form-label" for="basic-default-name">Age</label>
                <div class="col-sm-10">
                    {{form.age}}
                </div>
              </div>
              
              <div class="row mb-3">
                {% if form.jersey_number.errors %}
                  <div class="alert alert-danger mt-2" role="alert">
                    {{ form.jersey_number.errors }}
                  </div>
                {% endif %}
                <label class="col-sm-2 col-form-label" for="basic-default-name">Jersey Number</label>
                <div class="col-sm-10">
                    {{form.jersey_number}}
                </div>
              </div>
              
              <div class="row mb-3">
                {% if form.position.errors %}
                  <div class="alert alert-danger mt-2" role="alert">
                    {{ form.position.errors }}
                  </div>
                {% endif %}
                <label class="col-sm-2 col-form-label" for="basic-default-name">Position</label>
                <div class="col-sm-10">
                    {{form.position}}
                </div>
              </div>
              
                <hr/>
                <div class="modal-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
          </form>
        </div>
      </div>
  
    </div>
  </div>